"""constant.py"""

JSON_MODEL_NAME: str = "model_name"
JSON_TEXT: str = "text"
JSON_CURRENT_ITER: str = "current_iter"
JSON_TOTAL_ITER: str = "total_iter"
JSON_SIZE: str = "size"
JSON_HASH: str = "hash"
JSON_COMPLETE: str = "complete"
JSON_ABORT: str = "abort"
JSON_PRIORITY: str = "priority"
JSON_NUM_CLIENTS: str = "num_clients"
JSON_IMG_PATH: str = "img_path"
JSON_GIF_PATH: str = "git_path"

P_HASH_INIT: str = "00000000-0000-0000-0000-000000000000"