version: 2
jobs:
 build:
   machine: true
   environment:
      LANG: ja_JP.UTF-8
      LC_ALL: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
   steps:
     - checkout
     - setup_remote_docker:
        version: 19.03.13
        docker_layer_caching: true
     - run:
          name: Set locales
          command: sudo localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

     - run:
          name: Check current directory
          command: pwd

     # Build ddocker image
    #  - run: cd docker && ./build-docker.sh

     # Run docker container on the built image
    #  - run: ./run-docker.sh

workflows:
  version: 2
  workflows:
    jobs:
      - build