version: 2
jobs:
 build:
   machine: true
   environment:
      LANG: ja_JP.UTF-8
      LC_ALL: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
   steps:
     - checkout

     - run:
         name: Set locales
         command: sudo localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

     - run:
         name: Check current directory
         command: pwd

     - run: 
         name: Build docker image
         command: cd docker && ./build-docker.sh

workflows:
  version: 2
  workflows:
    jobs:
      - build