name: Docker-Pylint CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag aicon:$(date +%s) --build-arg HOSTNAME=$(hostname)
    - name: Run the docker container
      run: docker run -it --user="$(id -u):$(id -g)" --volume="aicon:/workspace:rw" --name="aicon" aicon:$(date +%s)
    - name: Install dependencies
      run: docker exec -it aicon pip install pylint
    - name: Analysing the code with pylint
      run: |
        docker exec -it aicon pylint /workspace/test -v -f colorized -r y
        docker exec -it aicon pylint /workspace/backend -v -f colorized -r y
