name: Docker-Pylint CI

on:
  push:
    branches: [ main, develop/**, feature/** ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag aicon:test --build-arg HOSTNAME=$(hostname)
    - name: Install dependencies
      run: |
        docker run --user="$(id -u):$(id -g)" --volume="aicon:/workspace:rw" --name="aicon" aicon:test
        docker exec aicon pip install pylint
    - name: Analysing the code with pylint
      run: |
        docker run --user="$(id -u):$(id -g)" --volume="aicon:/workspace:rw" --name="aicon" aicon:test
        docker exec aicon pylint /workspace/test -v -f colorized -r y
        docker exec aicon pylint /workspace/backend -v -f colorized -r y
