name: Docker Build CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag aicon:test --build-arg HOSTNAME=$(hostname)

