name: "Spell check workflow"
on: [ push ]

jobs:
  spell-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: sobolevn/misspell-fixer-action@master
        with:
          options: '-rsnouRVD .'
      - uses: peter-evans/create-pull-request@v3
        with:
          base: main
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
