name: "Spell check workflow"
on: [ push ]

jobs:
  spell-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: sobolevn/misspell-fixer-action@master
        with:
          options: '-snoV .'
      - uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
